apiVersion: v1
kind: Service
metadata:
  name: {{ template "application.name" . }}-service
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "application.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.containerPort }}