version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: ems
    ports:
      - "3306:3306"