{{ $app_name := env "APP_NAME" | default "ems-backend"}}


repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: mysql
  namespace: {{ $app_name }}
  chart: bitnami/mysql
  version: "9.14.3"
  values:
  - ./values/db/values.yaml